### ISSUE TITLE
Aero Fighters Assault - Startup Error

### ISSUE THREAD

**Issue by StenApp** [mupen64plus/mupen64plus-core#689]
Seems to be a mupen64plus core issue...

#https://github.com/gonetz/GLideN64/issues/2069

**Comment by Tasosgemah** [comment]
The older mupen64 core doesn't have this issue, don't know if that's useful information.

**Comment by loganmc10** [comment]
I think this is fixed now @StenApp can you confirm?

**Comment by StenApp** [comment]
@PixelCrusader please check if it works now

> When booting the game, the expected behavior is for the company logos and licensing information to fade from black, before transitioning into white and then into the planes flying.
> 
> ![AeroFighters Assault (USA)-190711-021651](https://user-images.githubusercontent.com/40935002/61031281-323bb200-a38d-11e9-8d47-18b19fbd9e2a.png)
> 
> Currently, booting the game almost completely cuts the company logos and licensing, prematurely changing into the planes flying.
> 
> This behavior was observed on Mupen64Plus-gui using the GLideN64 Public Release 4.0 as well as RetroArch's latest version of Mupen64Plus-Next, which uses a port of GLideN. Real hardware was used to confirm the discrepancy.
> 
> The example picture above was taken from RetroArch running an older version of their mupen64plus core (af7a4bf). This could mean that this is a regression.
> 
> Video of how the game should look:
> 
> https://www.youtube.com/watch?v=0ceyDL-bSR0&t=09s
> 
> https://www.youtube.com/watch?v=MhYAA8niTQM
> 
> https://www.youtube.com/watch?v=2C-ulZRmTT8

**Comment by PixelCrusader** [comment]
RetroArch 1.8.4, Mupen 64 Plus-Next Open GL (2.0 81a58df)

The problem persists, at least on my end. Logos begin to fade in, smash cut to planes.

**Comment by StenApp** [comment]
Could you build a Mupen64plus version? I don't know if the Mupen64plus-next core has fixed that issue...

**Comment by Jj0YzL5nvJ** [comment]
[Mupen64Plus-Next](https://github.com/libretro/mupen64plus-libretro-nx) is a completely different emulator and it's so heavily modified that save states are incompatible. The default core (master) has not been synchronized since 2019/03/03.
The most updated branch (rebase-core-gliden) was last synchronized on 2020/03/01 but you must compile it manually, and who knows if it works.

For Windows users, [m64p](https://github.com/loganmc10/m64p/releases) is the easiest solution to try. Or put together this cute jigsaw puzzle:
[mupen64plus-core](https://ci.appveyor.com/project/Narann/mupen64plus-core/builds/31961497)
[mupen64plus-ui-console](https://ci.appveyor.com/project/Narann/mupen64plus-ui-console/builds/31179936)
[mupen64plus-audio-sdl](https://ci.appveyor.com/project/Narann/mupen64plus-audio-sdl/builds/31650330)
[mupen64plus-input-sdl](https://ci.appveyor.com/project/Narann/mupen64plus-input-sdl/builds/31174116)
[mupen64plus-rsp-hle](https://ci.appveyor.com/project/Narann/mupen64plus-rsp-hle/builds/31174159)
[mupen64plus-video-gliden64](https://ci.appveyor.com/project/gonetz/gliden64/builds/31984091)

**Comment by m4xw** [comment]
> and it's so heavily modified that save states are incompatible

Actually the only reason savestates don't work is because I don't compress them so I don't have a gzip dependency.

>  and who knows if it works.

It's release ready since the day it was written, didn't clean it up yet & merge tho due to time issues.
But yea, people using the wrong repo for bugreports /shrug

**Comment by m4xw** [comment]
Also I should note, we don't build my master branch for the buildbot.

**Comment by Jj0YzL5nvJ** [comment]
Interesting, I can load uncompressed save states from master and OpenEmu but not from Mupen64Plus-Next.

**Comment by m4xw** [comment]
Mupen Core does not support uncompressed savestates.

**Comment by Jj0YzL5nvJ** [comment]
If you extract it with 7-Zip you can. #591

**Comment by m4xw** [comment]
Your master's savestate version is likely higher?

**Comment by m4xw** [comment]
Also fwiw I just cleaned up, bumped master and prepared the RC, so if anyone actually wants to test https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/pipelines/5051/builds
This is a intermediate release before I pull in each and every recent change.

**Comment by Jj0YzL5nvJ** [comment]
> Your master's savestate version is likely higher?

I'm not sure... it works even with old save states.
https://0x0.st/iSZl.7z

**Comment by m4xw** [comment]
You can find all changes related to savestates here https://github.com/libretro/mupen64plus-core/commit/7396848997a81be31f940b19fff24860c4305ecd#diff-1e33528d649efca1d3d10f4dfb241be8
If older version standalone savestates, uncompressed, don't load on NX, then something is up.

**Comment by Jj0YzL5nvJ** [comment]
It's the other way around, `mupen64plus-ui-console` doesn't load Mupen64Plus-Next save states.
I haven't compiled RetroArch in a looooooong time. [I no longer have save states that marked an audio related error...](https://github.com/gonetz/GLideN64/issues/2152#issuecomment-601648425)

Give me a current NX save state and so we both left doubts. `Resident Evil 2 (U) (V1.1) [!]` like the original report.

**Comment by m4xw** [comment]
Well, yes, because the savestates aren't compressed, so mupen will fail decompressing them.
At work so I cant provide you with a state rn.

**Comment by m4xw** [comment]
Headers _are_ identical, since, forever.
File size's _are_ identical too.
Whatever your issue was must be a upstream issue with save conversion, or maybe it has issues with older dynarec states loaded into interpreter

**Comment by m4xw** [comment]
Heres a majoras state if u really wanna test [Legend of Zelda, The - Majora's Mask (E) (M4) (V1.1).zip](https://github.com/mupen64plus/mupen64plus-core/files/4451269/Legend.of.Zelda.The.-.Majora.s.Mask.E.M4.V1.1.zip)
`f760c811e02b4951873a5919b3a1c84fda68e5042aa5d9f69ee8368ac72b0297 *Legend of Zelda, The - Majora's Mask (E) (M4) (V1.1).z64`
Savestate ver 0x00010600

**Comment by Jj0YzL5nvJ** [comment]
Ok, it loads. My bad.

**Comment by m4xw** [comment]
Now I am curious tho what actually caused it.
Also fwiw I stand corrected with fail to decompress the data

>  If the file is not compressed, gzread() shall simply copy data from file to buf without alteration.

**Comment by PixelCrusader** [comment]
RetroArch 1.8.4 - Mupen64Plus-Next OpenGL (2.0.5 08247ba) i.e. https://git.m4xw.net/libretro/cores/mupen64plus-libretro-nx/pipelines/5051/builds

The problem is resolved. The logos and license text display properly without being interrupted.

**Comment by loganmc10** [comment]
Mupen-next/retroarch shouldn't be used to test against this repo, but I did test mupen64plus and this has been resolved since the changes to the interrupt timing

**Comment by PixelCrusader** [comment]
Okay, sorry. I downloaded https://github.com/loganmc10/m64p/releases/tag/Apr012020

The problem is resolved. The logos and license text display properly without being interrupted.
